import type { CashClosingData } from "@/types/cash-closing";

export const mockCashClosingData: CashClosingData = {
  shift: {
    id: "shift-morning-001",
    name: "Turno matutino",
    responsibleName: "Ana López",
    startedAt: "Hoy, 8:00 a. m.",
    scheduledEndAt: "Hoy, 4:00 p. m.",
    currentDuration: "7 h 42 min",
  },
  openingBalance: 5000,
  reservedCash: 3500,
  movements: [
    {
      id: "movement-in-1",
      folio: "DEP-00210",
      category: "cash_deposit",
      direction: "in",
      description: "Efectivo recibido por depósito",
      amount: 5000,
      registeredAt: "Hoy, 9:05 a. m.",
      registeredBy: "Ana López",
    },
    {
      id: "movement-in-2",
      folio: "DEP-00211",
      category: "cash_deposit",
      direction: "in",
      description: "Efectivo recibido por depósito",
      amount: 5000,
      registeredAt: "Hoy, 10:18 a. m.",
      registeredBy: "Ana López",
    },
    {
      id: "movement-in-3",
      folio: "COM-00031",
      category: "commission",
      direction: "in",
      description: "Comisiones cobradas en efectivo",
      amount: 2800,
      registeredAt: "Durante el turno",
      registeredBy: "Sistema",
    },
    {
      id: "movement-out-1",
      folio: "RET-00120",
      category: "delivered_withdrawal",
      direction: "out",
      description: "Retiro entregado al cliente",
      amount: 2500,
      registeredAt: "Hoy, 11:20 a. m.",
      registeredBy: "Ana López",
    },
    {
      id: "movement-out-2",
      folio: "RET-00121",
      category: "delivered_withdrawal",
      direction: "out",
      description: "Retiro entregado al cliente",
      amount: 2000,
      registeredAt: "Hoy, 12:45 p. m.",
      registeredBy: "Carlos Ruiz",
    },
    {
      id: "movement-out-3",
      folio: "OWNER-0008",
      category: "owner_withdrawal",
      direction: "out",
      description: "Retiro de efectivo del propietario",
      amount: 850,
      registeredAt: "Hoy, 2:10 p. m.",
      registeredBy: "Propietario",
    },
  ],
};