import type { Operation } from "@/types/operation";
import type {
  ReceiptBusinessIdentity,
  ReceiptPreferences,
} from "@/types/receipt";

export const initialBusinessIdentity: ReceiptBusinessIdentity = {
  businessName: "PAPELERÍA ADONAI",
  phone: "",
  address: "",
};

export const initialReceiptPreferences: ReceiptPreferences = {
  paperSize: "80mm",
  copies: 1,
  autoOpenAfterRegister: true,
  fieldVisibility: {
    showBusinessName: true,
    showOperationType: false,
    showDate: true,
    showTime: false,
    showAmount: true,
    showCommission: false,
    showTotal: false,
    showFolio: true,
    showOperationId: false,
    showBank: false,
    showSender: true,
    showReceiver: true,
    showBeneficiary: false,
    showRegisteredBy: false,
    showDeliveredBy: false,
    showResponsibleUser: false,
    showStatus: false,
    showEditedIndicator: false,
    showObservations: false,
    showSignatureSpace: true,
    showPhone: false,
    showAddress: false,
    showHeaderMessage: false,
    showFooterMessage: false,
    showClarificationMessage: false,
  },
  headerMessage: "",
  footerMessage: "",
  clarificationMessage: "",
};

export const receiptPreviewOperations: Record<string, Operation> = {
  completedDeposit: {
    id: "preview-deposit-completed",
    type: "deposito",
    status: "entregado",
    amount: 2500,
    commission: 10,
    total: 2510,
    bankFrom: "Efectivo",
    bankTo: "Banco Azteca",
    bankFolio: "123456",
    senderName: "Juan Pérez",
    receiverName: "María López",
    createdBy: "Empleado 1",
    createdAt: "2026-08-04T11:30:00",
    isEdited: false,
  },
  pendingDeposit: {
    id: "preview-deposit-pending",
    type: "deposito",
    status: "pendiente",
    amount: 2500,
    commission: 10,
    total: 2510,
    bankFrom: "Efectivo",
    bankTo: "Banco Azteca",
    bankFolio: "123456",
    senderName: "Juan Pérez",
    receiverName: "María López",
    createdBy: "Empleado 1",
    createdAt: "2026-08-04T11:30:00",
    isEdited: false,
  },
  deliveredWithdrawal: {
    id: "preview-withdrawal-delivered",
    type: "retiro",
    status: "entregado",
    amount: 2500,
    commission: 10,
    total: 2510,
    bankFrom: "Banco Azteca",
    bankTo: "Efectivo",
    bankFolio: "123456",
    senderName: "Juan Pérez",
    receiverName: "María López",
    createdBy: "Empleado 1",
    createdAt: "2026-08-04T11:30:00",
    isEdited: false,
  },
  pendingWithdrawal: {
    id: "preview-withdrawal-pending",
    type: "retiro",
    status: "pendiente",
    amount: 2500,
    commission: 10,
    total: 2510,
    bankFrom: "Banco Azteca",
    bankTo: "Efectivo",
    bankFolio: "123456",
    senderName: "Juan Pérez",
    receiverName: "",
    createdBy: "Empleado 1",
    createdAt: "2026-08-04T11:30:00",
    isEdited: false,
  },
};
