import type { AdministrativeMovement } from "@/types/administrativeMovement";

export const initialAdministrativeMovements: AdministrativeMovement[] = [
  {
    id: "adm-mov-001",
    movementType: "income",
    resourceType: "cash",
    resourceId: "cash",
    resourceName: "Caja física",
    amountCents: 150000,
    balanceBeforeCents: 1095000,
    balanceAfterCents: 1245000,
    explanation: "Ingreso administrativo mock a caja física.",
    createdByUserId: "carlos-martinez",
    createdByUserName: "Carlos Martínez",
    createdAt: "2026-08-05T09:10:00",
    shiftId: "shift-current",
    status: "active",
    isEdited: false,
  },
  {
    id: "adm-mov-002",
    movementType: "withdrawal",
    resourceType: "bank",
    resourceId: "bank-bbva",
    resourceName: "BBVA",
    amountCents: 50000,
    balanceBeforeCents: 300000,
    balanceAfterCents: 250000,
    explanation: "Retiro administrativo mock de BBVA.",
    createdByUserId: "alex-hernandez",
    createdByUserName: "Alex Hernández",
    createdAt: "2026-08-05T10:05:00",
    shiftId: "shift-current",
    status: "active",
    isEdited: false,
  },
  {
    id: "adm-mov-003",
    movementType: "income",
    resourceType: "bank",
    resourceId: "bank-azteca",
    resourceName: "Banco Azteca",
    amountCents: 200000,
    balanceBeforeCents: 2300000,
    balanceAfterCents: 2500000,
    explanation: "Ingreso administrativo mock a Banco Azteca.",
    createdByUserId: "carlos-martinez",
    createdByUserName: "Carlos Martínez",
    createdAt: "2026-08-05T11:20:00",
    shiftId: "shift-current",
    status: "active",
    isEdited: false,
  },
  {
    id: "adm-mov-004",
    movementType: "withdrawal",
    resourceType: "cash",
    resourceId: "cash",
    resourceName: "Caja física",
    amountCents: 80000,
    balanceBeforeCents: 1325000,
    balanceAfterCents: 1245000,
    explanation: "Retiro administrativo mock de caja física.",
    createdByUserId: "alex-hernandez",
    createdByUserName: "Alex Hernández",
    createdAt: "2026-08-05T12:15:00",
    shiftId: "shift-current",
    status: "active",
    isEdited: false,
  },
];
