import type { UserAccount } from "@/types/user";

export const initialUserAccounts: UserAccount[] = [
  {
    id: "carlos-martinez",
    firstName: "Carlos",
    lastName: "Martínez",
    displayName: "Carlos Martínez",
    username: "carlos.martinez",
    systemRole: "owner",
    status: "active",
    createdAt: "2026-07-01T09:00:00",
    lastLogin: "today",
    temporaryPassword: "Temp-8624",
    internalNotes: "Cuenta de dueño administrada en mock.",
    authUserId: undefined,
    profileId: "profile-carlos-martinez",
    passwordRecoveryStatus: "not_configured",
    sessionsReady: false,
  },
  {
    id: "alex-hernandez",
    firstName: "Alex",
    lastName: "Hernández",
    displayName: "Alex Hernández",
    username: "alex.hernandez",
    systemRole: "owner",
    status: "active",
    createdAt: "2026-07-01T09:10:00",
    lastLogin: "today",
    temporaryPassword: "Temp-4179",
    internalNotes: "Cuenta de dueño administrada en mock.",
    authUserId: undefined,
    profileId: "profile-alex-hernandez",
    passwordRecoveryStatus: "not_configured",
    sessionsReady: false,
  },
  {
    id: "juan-perez",
    firstName: "Juan",
    lastName: "Pérez",
    displayName: "Juan Pérez",
    username: "juan.perez",
    systemRole: "employee",
    status: "active",
    createdAt: "2026-07-02T10:00:00",
    lastLogin: "yesterday",
    temporaryPassword: "Temp-5038",
    internalNotes: "Empleado con acceso operativo.",
    authUserId: undefined,
    profileId: "profile-juan-perez",
    passwordRecoveryStatus: "not_configured",
    sessionsReady: false,
  },
  {
    id: "ana-lopez",
    firstName: "Ana",
    lastName: "López",
    displayName: "Ana López",
    username: "ana.lopez",
    systemRole: "employee",
    status: "suspended",
    createdAt: "2026-07-03T11:00:00",
    lastLogin: "never",
    temporaryPassword: "Temp-2941",
    internalNotes: "Cuenta suspendida en mock.",
    authUserId: undefined,
    profileId: "profile-ana-lopez",
    passwordRecoveryStatus: "not_configured",
    sessionsReady: false,
  },
];
